# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  paths:
    include:
    - ParkPal.NotificationService/*

pool:
  name: 'Windows Pool'


variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    targetPath: '$(Pipeline.Workspace)'

- task: NuGetToolInstaller@1
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.400'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)\ParkPal.NotificationService\ParkPal.NotificationService.sln'

    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '-c Release --sc'
    publishWebProjects: false
    projects: '$(Build.SourcesDirectory)\ParkPal.NotificationService\ParkPal.NotificationService.sln'
    
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Build.SourcesDirectory)\ParkPal.NotificationService\ParkPal.NotificationService\bin\Release\**\**\publish.zip'
    destinationFolder: 'C:\staging\ParkPal.NotificationService\'
    cleanDestinationFolder: true
    overwriteExistingFiles: true