<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Data.SqlClient" Version="5.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.1" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
      <PackageReference Include="RestSharp" Version="108.0.2" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Database\Scripts\UpgradeScript_1.0.0.dbu">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Database\Scripts\UpgradeScript_1.0.1.dbu">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
