# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  paths:
    include:
      - ParkPal.Website/*

pool:
  name: 'Linux Pool'

steps:
- task: CmdLine@2
  inputs:
    script: |
      ls

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'


- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'ParkPal.Website'
  displayName:  'Install Project'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run-script build'
    workingDir: 'ParkPal.Website'
  displayName: 'Build Project'
