# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  name: 'Linux Pool'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm --prefix $(Build.SourcesDirectory)/ParkPal.Application install
    npm --prefix $(Build.SourcesDirectory)/ParkPal.Application run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/ParkPal.Application'
    Contents: 'dist/**'
    TargetFolder: '/staging/'
    OverWrite: true
    CleanTargetFolder: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/ParkPal.AppIcons'
    Contents: '**'
    TargetFolder: '/staging/'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/ParkPal.Application'
    Contents: '\package.json'
    TargetFolder: '/staging/'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/ParkPal.Application'
    Contents: '\capacitor.config.ts'
    TargetFolder: '/staging/'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/ParkPal.Application'
    Contents: '\ionic.config.json'
    TargetFolder: '/staging/'
    OverWrite: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '/staging/'
    publishLocation: 'pipeline'
